# Generated by Django 4.2.4 on 2024-06-16 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0003_alter_poema_user_id_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poema',
            name='user_id_favorito',
        ),
        migrations.AddField(
            model_name='poema',
            name='user_id_favorito',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
